import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbars/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "@/components/shared/Providers";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "PONCHOVUJ - Online store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
